### ISSUE TITLE
"Open with..." selection can't be saved

### ISSUE THREAD

**Issue by bighlion** [jaap-karssenberg/zim-desktop-wiki#208] opened 2017-09-20 19:47 UTC
I can't open PDF files with Okular. I've tried _Open with... -> Okular (or System default) -> Close_ but the settings aren't saved this way, and PDF files are still being opened by the Document Viewer.

![image](https://user-images.githubusercontent.com/27025774/30663800-1b00d11c-9e4c-11e7-9e49-79a8a95b5cfb.png)

**Comment by jaap-karssenberg** [comment] 2017-11-02 20:15
Can't reproduce this issue, can you run zim as "zim --debug" and do this action?  The debug output should reveal the config files being read and written.

**Comment by jaap-karssenberg** [comment] 2019-01-11 08:14
Closing for now. Please re-open if you have information how to reproduce and/or debug output.

**Closed by jaap-karssenberg** 2019-01-11 08:14 UTC
Labels: needs info
