### ISSUE TITLE
error encountered when I deleted a file and undo it

### ISSUE THREAD

**Issue by kattak2k** [jaap-karssenberg/zim-desktop-wiki#226] opened 2017-11-09 22:32 UTC
Hi team,
my zim stopped working because of below issue. I had all my data in it and I'm afraid that I might loose it.

This is zim 0.67
Platform: posix
Locale: en_IN ISO8859-1
FS encoding: UTF-8
Python: (2, 7, 14, 'final', 0)
Gtk: (2, 24, 31)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "/usr/lib/python2.7/dist-packages/zim/gui/widgets.py", line 3203, in do_response
    destroy = self.do_response_ok()
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 2573, in do_response_ok
    self.app_window.ui.open_page(page)
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 730, in open_page
    raise AssertionError, 'Could not close page'
AssertionError: Could not close page

**Comment by Osndok** [comment] 2017-11-10 04:41
To assuage your fears, one of the beautiful aspects of Zim is that it does not lock away your data in any kind of proprietary format, or even obscure database... all the files are laid out, bare, in your Notebooks directory.

Furthermore, you might be interested in keeping the notebook under version control. With that enabled, incremental backups become trivial, and it is next to impossible to actually lose any data.

More to the point, it sounds like zim has some stale state. I would recommend:
1. moving /tmp/zim-${YOUR_USERNAME} aside, and
2. restarting your computer (just for good measure, as a stuck zim background thread might be running)

**Comment by kattak2k** [comment] 2017-11-10 08:03
Thank you for your prompt, I indeed lost my saved files. I did versioning as you've mentioned.

I tried to reproduce the bug.. here are the steps..
1. In a file add a tag  +new/file , hit enter 
2. and then replace the name with +new_file and press enter again
4. you might see 3 filed created one with name "new file" and other with "new_file"
5, delete any one of the files, you'll see both the files gets deleted.
6. and I kept on adding stuff to new_file and deleted the "new file" as I do not requre it. boom !! I lost everything.

Hope this helps to fix.

I have restarted my machine hoping that things would work fine, but the lost files which I created. :(

**Comment by Osndok** [comment] 2017-11-10 08:34
It sounds like you are describing a case where the pagename-to-filename conversion "collides" because **spaces are replaced by underscores**. I see now, that probably the "last page to be saved" one, and your first post (with the stack trace) makes sense.

I **was** able to replicate this sort of failure, and found a similar fault with page names that **differ only by case**.

In my testing, I had to delete all conflicting pages to return zim's database to a consistent state (although rebuilding the index probably would have worked too).

I'm sorry for your data loss. Hopefully that will not dissuade you from continuing your zim experimentation.

**Comment by jaap-karssenberg** [comment] 2017-12-13 05:39
Duplicate of #183

**Closed** 2017-12-13 05:40 UTC
Labels: needs investigation, prio critical
