### ISSUE TITLE
Suppress automatic creation of Pages

### ISSUE THREAD

**Issue by ekw** [jaap-karssenberg/zim-desktop-wiki#233] opened 2017-11-22 18:19 UTC
When I have "A:B:C" in a page, this gets interpreted as a link and pages A, B and C are created greyed out.  I can right-click and choose Remove Link and the text is de-linked and the greyed out pages are no longer auto-created when Zim Wiki is restarted. 

Email addresses are always linked, though no page is created.  Rather, an email link causes email client to execute when clicked upon.  Doing "Remove Link" appears to de-link the text, but the email address becomes linked once again when the page is re-opened.

Combining the above, any "A:B:C" text where one of A/B/C is an email address always causes the greyed out pages to be created, even after Remove Link is performed.  I can live with email addresses always being linked, but don't want the greyed out pages to always be automatically created.

Is there any way to turn off the automatic linking of email address and/or creation of pages?  Under Edit-->Preferences-->Editing, I turned off all the "Automatically turn ... into links" options as well as turned off "Reformat wiki markup on the fly", but this still occurs.  I am using v0.67.  

Thanks for any help.

**Comment by haeckle** [comment] 2017-11-22 22:46
I think that's duplicate of #80

**Comment by ekw** [comment] 2017-11-22 23:11
It is related and I'm glad to see #80 slated for 0.68, as it will work for my use case. But I think there is a additional subtle bug here, or at least an inconsistency.  When you remove link on "page1:page2:page3", re-opening the page will not cause the link to come back.  When you remove link on an email address, re-opening the page will recreate the link.

**Comment by jaap-karssenberg** [comment] 2017-12-11 15:53
Yes the subtle bug is that you should not be able to do "remove link" on email addresses.

Reason for this is that email addresses are always recognized as such by the wiki parser, while page links need additional "`[[...]]`" wrapper to turn them in a link. We can remove the wrapper, but we can't make an email address be not an email address.

**Closed** 2017-12-11 15:54 UTC
Labels: duplicate
