### ISSUE TITLE
Working on two documents (pages) in paralle inside same notebook

### ISSUE THREAD

**Issue by lowk3y** [jaap-karssenberg/zim-desktop-wiki#212] opened 2017-09-27 09:20 UTC
Right now you can open specific page in new window as read-only (view mode); but it would be great if you could have split view of page view and be able to edit two documents at the same time. I hope I am cleared enough about this feature request.

**Comment by jaap-karssenberg** [comment] 2017-12-11 17:14
This is a duplicate of #153

**Closed** 2017-12-11 17:14 UTC
Labels: duplicate
