### ISSUE TITLE
URL causing crash

### ISSUE THREAD

**Issue by Simplenuity** [jaap-karssenberg/zim-desktop-wiki#146] opened 2017-07-07 21:09 UTC
I'm observing the following:

Either:
As soon as I paste an URL (starting with http or https) into a page Zim crashes.

Or:
If I externally edit the page (while Zim is not running) and paste in the URL, then try to start Zim, it fails.

Both cases trigger the following error:

```
INFO: This is zim 0.67-rc2
INFO: Open page: GTD-0-1:Next-Actions:work (GTD-0-1:Next-Actions:work)
/usr/lib/python2.7/dist-packages/gtkspellcheck/spellcheck.py:548: GtkWarning: /build/gtk+2.0-KsZSEA/gtk+2.0-2.24.23/gtk/gtktextbtree.c:4096: char offset off the end of the line
  end = self._buffer.get_iter_at_line_offset(start.get_line(), match.end())

(zim:8623): Gtk-ERROR **: Char offset 32 is off the end of the line
Trace/breakpoint trap
```
Obviously the process number (zim:8623) is always changing.

System: Linux Lite 2.8 (based on Ubuntu 14.04)

Please let me know what other information is needed for trouble shooting.

Thanks for that great program and steady development!

UPDATE: I did some more testing and found out that it is the dot "." in the URL causing the crash. Any URL starting with http://, https:// or ftp:// causes the crash as soon as I type in "." within the address.

**Comment by jaap-karssenberg** [comment] 2017-07-10 06:45
I believe this is a duplicate of issue #72

**Comment by Simplenuity** [comment] 2017-07-10 19:41
Hi Jaap,
Thanks for looking into it.
I can confirm that toggling the spell check does make a difference, meaning turning spell check off is avoiding the crash.
Interestingly the crash is not consistently reproducible across different pages within one notebook. That means adding an URL to one page is causing the crash while adding the exact same link to another page is OK.

Thanks for pointing me into the right direction to at least have a workaround.

**Closed** 2017-07-11 10:30 UTC
Labels: duplicate
