### ISSUE TITLE
Re-enable native macOS menus

### ISSUE THREAD

**Issue by brechtm** [jaap-karssenberg/zim-desktop-wiki#22] opened 2017-05-05 14:29 UTC
See #20 for discussion.

**Comment by Kreisleriana** [comment] 2017-05-11 12:37
Mac user here, I am not a coder but can help testing once a candidate solution has been implemented. Thanks for making an effort!

**Comment by jaap-karssenberg** [comment] 2017-05-11 17:48
Tried implementing this as a plugin. See link below for what I came up with. Not tested on actual OS X, so probably fails on first try, but hopefully easy enough to get it to work :crossed_fingers: 

https://gist.github.com/jaap-karssenberg/c0fd050613173ee3b0ab14797ea86f29

**Comment by brechtm** [comment] 2017-05-11 21:17
I gave it a quick spin and it worked on the first try! I tried opening a second notebook, which seems to work fine. I'll use this version to see if any problems pop up, but I'm not using Zim on OS X as much these days...

Is there a particular reason you implemented it as a plugin? I would think the OS X menu should always be enabled on OS X.

**Comment by jaap-karssenberg** [comment] 2017-05-12 07:12
Reason to do it as a plugin to keep the app modular. Also I like this mechanism for functions that have optional dependencies, because the user can see in the plugin list why something is disabled. I can make it a default plugin on OS X.

How about the "TODO" items in the file?

- [x] Test switching between windows
- [ ] Test what if first window is closed
- [ ] Do we need to hide the "Help" menu from the menubar ?
- [ ] Do we need to hide the "quit" / "about" / "preferences" items from the menubar ?

**Comment by Kreisleriana** [comment] 2017-05-12 08:46
Hi all

I can confirm that it works on two computers (both version 0,66 Zim and macOS Sierra). Good work, thank you!


A couple of observations:
Although OS X is still used frequently, in the future the now official macOS name will be used (and searched for) more often, maybe consider renaming
Once the menubar plugin is enabled starting Zim sometimes takes way longer as if there was a preset time was counted now without much happening (around 30s). I haven’t yet found why it sometimes happens and sometimes not.
I can quit using the shortcut Cmd-Q but there are two “quit” menu items, one under Python (to which the shortcut is bound) and another under file which achieves the same. If necessary to close one notebook only, it should perhaps be renamed “close notebook”.
The windows are now behaving correctly and appear as windows of the application “Python” (useful for resizing and positioning by shortcut for example)
Not sure if possible but could the application actually appear as “Zim” instead of Python? 

Will continue testing but need to work first, thanks again

Christoph

**Comment by brechtm** [comment] 2017-05-12 09:00
I didn't spot the TODO items before. I did some more tests. Here are my findings:

1. When a single notebook window is open and it is closed, the application quits. This is not in line with most macOS applications. Ideally, the Zim menu bar should survive and allow opening a new notebook for example. That said, there are some other applications that behave like this. (minor issue)

2. Unlike 0.65, Zim will now start in the non-standalone mode without crashing. Although sometimes it takes a very long time before the notebook window is opened. Does it fall back to standalone mode in that case? I haven't been able to reproduce this delay when writing this.

2. In standalone mode, opening a second notebook window creates another app icon in the "task bar" (I forgot the macOS name for it). Closing the first window quits the first process and returns to the shell.

3. If the preferences window is opened (which has no menu), the notebook's menu is still shown. This is in line with other macOS applications. When opening another notebook by clicking the "More" button for a plugin, a new notebook opens (in the background). Activating the new notebook makes the menu bar flash once, but it functions as expected.

4. The first time I did the above, after closing the new notebook window, the focus was restored to the Preferences window and the menu entries disappeared (except for the default Python menu). I cannot reproduce this though.

5. The "help" menu does not need to be hidden. The "about" and "preferences" items should be moved to the appropriate locations and "quit" should be hidden (as in my original code). I can have a look at this later, but no promises at as to when.

Thanks for your work, Jaap! This makes Zim again at least as nice on macOS as 0.65.

**Comment by brechtm** [comment] 2017-05-12 09:02
> Not sure if possible but could the application actually appear as “Zim” instead of Python?

IIRC I had a look at this before but without success, so it may not be that easy. It would also be nice to display the Zim icon in the task bar instead of the Python rocket.

**Comment by jaap-karssenberg** [comment] 2017-05-12 12:06
> The "help" menu does not need to be hidden. The "about" and "preferences" items should be moved to the appropriate locations and "quit" should be hidden (as in my original code). I can have a look at this later, but no promises at as to when.

I can make these changes, just need some guidance where "about" and "preferences" should go.

-- Jaap

**Comment by Kreisleriana** [comment] 2017-05-12 12:10
In macOS, one would normally expect to find both (about and Preferences) under “python” (or “Zim” if possible) with “about" being the topmost entry and “Preferences" not too far down.

**Comment by jaap-karssenberg** [comment] 2017-05-12 13:03
Not entirely sure I get it right - the default menubar does not have a "python" or "zim" menu, but has "File" as left most item. Do the contents of this "python" menu map to the contents of "File" without the plugin?  If so I can just move them there, if not, I need to understand how this menu is generated.

The plugin already calls "insert_app_menu_item()" for both About (position 1) and Preferences (position 2)  - lines 113 to 117 - does this have any effect on the content of the "python" menu?


I'm just guessing here - can't find documentation for gtkosx_application online, so not even sure what the functions do ...

**Comment by Kreisleriana** [comment] 2017-05-12 13:13
I cannot tell how the menu immediately to the left of the Apple icon in the menu bar is generated but neither the about nor preferences would be expected under the File menu in macOS if that is what you are asking. 
Here is Mail as an example:



Sorry, I am not a programmer, just a grateful “customer” so unfortunately I cannot guide you there, maybe Brecht can.

**Comment by brechtm** [comment] 2017-05-12 14:23
The application (Python) menu is generated automatically by macOS, but items can be added to it:

![screen shot 2017-05-12 at 16 19 51](https://cloud.githubusercontent.com/assets/652887/26002137/ef0a48ce-372e-11e7-928a-0076eb486e7a.png)

My original code for adding native macOS support ([commented out here](https://github.com/jaap-karssenberg/zim-desktop-wiki/commit/be1e73ff954812510ccaa07903cb902be627b0bd)) moves the appropriate items to the application menu.

**Comment by jaap-karssenberg** [comment] 2017-05-12 14:35
@brechtm thanks - this helps me to visualize :)

Just spotted a bug in my code - changed one line, please try the new version: https://gist.github.com/jaap-karssenberg/c0fd050613173ee3b0ab14797ea86f29

Expect new the about and preferences are in the "Python" menu, but also in the original menu. Also might expect the "Help" menu to show up twice. If this is the case, I only have to hide the original versions :)

**Comment by brechtm** [comment] 2017-05-12 15:05
Nope, "about" and "preferences" do not appear in the application menu. They do still appear in the File and Edit menus. I do see this error, however:

`(zim.py:35991): gtkosxapplication-CRITICAL **: gtkosx_application_set_help_menu: assertion 'cocoa_menubar != NULL' failed`

I also see these:

```
/Users/brechtm/Documents/Code/zim-desktop-wiki/zim/plugins/osx_menubar.py:140: Warning: invalid cast from 'GtkMenuBar' to 'GtkWindow'
  _global_osx_application.set_menu_bar(self.menubar)
/Users/brechtm/Documents/Code/zim-desktop-wiki/zim/plugins/osx_menubar.py:140: GtkWarning: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
  _global_osx_application.set_menu_bar(self.menubar)
```

But these were also output on Zim 0.65 where the items do show up in the application menu.

**Comment by brechtm** [comment] 2017-05-12 15:29
Also, quitting Zim through the application menu "Quit" or the shortcurt Cmd+q raises an exception:

`AttributeError: 'MainWindow' object has no attribute 'quit'`

But Zim still quits.

I'm not sure how to get at the `GtkInterface` object on which `quit()` was called in Zim 0.65.

**Comment by brechtm** [comment] 2017-05-12 15:30
I tried to see why the about and prefs menu items won't show up in the application menu, but I can't find any clues.

**Comment by jaap-karssenberg** [comment] 2017-05-18 08:55
Updated the plugin: https://gist.github.com/jaap-karssenberg/c0fd050613173ee3b0ab14797ea86f29

* Fixes the call for "quit()"
* Moved the initialization of the global items to a later moment in time, not sure whether this makes a difference or not

**Comment by jaap-karssenberg** [comment] 2017-05-18 09:15
Just set the milestone for this issue to the 0.67 release (which should be released as-soon-as-practical) because it is a regression compared to 0.65 when this is missing. 

Would like @brechtm to sign off that this plugin is good / good enough to include and enable by default for Mac OS. At least it should not break usability of zim, even though menus may require fine-tuning in next release etc.

**Comment by brechtm** [comment] 2017-05-19 09:08
The quit() issue is indeed fixed. The menus still do not show up in the application menu. But I do agree that it works well enough for inclusion in 0.67.

There seem to be some more warnings being output:
```
$ python zim.py
INFO: This is zim 0.66
2017-05-19 11:03:19.893 Python[52345:3639770] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
INFO: Using default notebook: file:///Users/brechtm/Dropbox/zim
INFO: VCS detected: git - /Users/brechtm/Dropbox/zim
INFO: Open page: Entertainment:Food (Entertainment:Food)

(zim.py:52345): gtkosxapplication-CRITICAL **: gtkosx_application_set_help_menu: assertion 'cocoa_menubar != NULL' failed
/Users/brechtm/Documents/Code/zim-desktop-wiki/zim/plugins/osx_menubar.py:137: Warning: invalid cast from 'GtkMenuBar' to 'GtkWindow'
  _global_osx_application.set_menu_bar(self.menubar)
/Users/brechtm/Documents/Code/zim-desktop-wiki/zim/plugins/osx_menubar.py:137: GtkWarning: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
  _global_osx_application.set_menu_bar(self.menubar)
/Users/brechtm/Documents/Code/zim-desktop-wiki/zim/gui/__init__.py:1902: Warning: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
  Window.destroy(self) # gtk destroy & will also emit destroy signal
/Users/brechtm/Documents/Code/zim-desktop-wiki/zim/plugins/__init__.py:783: GtkWarning: gtk_ui_manager_remove_action_group: assertion 'g_list_find (self->private_data->action_groups, action_group) != NULL' failed
  self.window.uimanager.remove_action_group(self.actiongroup)
```

**Closed** 2017-06-12 13:15 UTC
Labels: fix committed, needs testing
