### ISSUE TITLE
Code Fences

### ISSUE THREAD

**Issue by sathishkumar-in** [jaap-karssenberg/zim-desktop-wiki#271] opened 2017-12-26 03:59 UTC
I use zim wiki to store code snippets.
It would be better if it has a code fence similar to markdown. It would be a visual indication that it is code.
~~~C
print()
~~~

Currently, I use bold & Pre formats to distinguish them. But Code fence with the gray background would be a lot better. Thanks

**Comment by Osndok** [comment] 2017-12-26 04:12
Dupe of #157 ... zim does have such a thing, but it is currently a bit more verbose, and usually summonded from the 'insert' menu after the 'source view' plugin is installed (which also requires an apt-get or 'dnf install').

```

{{{code: lang="java" linenumbers="True"
package some.thing;

class MyClass
{

}
}}}
```

**Comment by sathishkumar-in** [comment] 2017-12-26 04:18
Thanks..I will look into it

**Comment by Osndok** [comment] 2017-12-26 04:51
Happy to help, and glad to see feedback.

If you happened to look at the documentation for an a answer to this first, consider submitting a pull request with doc-changes that would have helped you find it.

Also, if that plugin and/or 157 meets your needs, you should probably close this ticket.

**Closed** 2017-12-26 06:58 UTC
