### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by robgordon001** [jaap-karssenberg/zim-desktop-wiki#237] opened 2017-11-26 20:19 UTC
Great product - but this is an annoying bug.   I want to use the daily journal as a "scratch pad" and keep it open in a separate window, but unlike other docs in Zim this one will not allow editing.

**Comment by Osndok** [comment] 2017-11-26 22:32
Dupe of #153 ... due to how the code is laid out, it's actually a bit of work, but it's on the radar!

**Closed** 2017-12-11 14:16 UTC
Labels: duplicate
