### ISSUE TITLE
Links not cleaned up correctly in index after moving or renaming

### ISSUE THREAD

**Issue by sojusnik** [jaap-karssenberg/zim-desktop-wiki#85] opened 2017-05-31 14:50 UTC
When a page (f.i. ":Universe") with a text link (only done with "+Alpha Centauri", not "Universe:Alpha Centauri") to its subpage ("Universe:Alpha Centauri") is manually moved to another page, then the page remains at its initial position, but is grayed out and italic (like you have when using "go to" to a new page). Manually deleting this grayed out and italic page isn't possible. Rebuilding the index doesn't help either.

This started after updating to the recent 0.66 version.

Is, imho, a critical bug.

**Comment by mnordlin** [comment] 2017-06-04 07:46
I have this bug too: In post-0.66 I've moved a folder of some pages and the move was successful. The gray page references remain in the index, however. The problem cannot be temporarily resolved by opening the zim notebook in zim V0.65 (on the same PC, not even if you re-index the notebook): The gray pages are not shown on the pages where they were previously, before the move, but they're still there when you open the notebook in post-0.66 again. The gray pages (and sub-pages) cannot be deleted, and only contains backlinks to the grayed-out parent page. (I think I read in the manual a long time ago that this is not a bug, but expected behaviour. But the gray pages used to disappear eventually, which they don't do now.)

**Closed** 2017-06-08 19:39 UTC
Labels: bug, needs investigation
