### ISSUE TITLE
Feature Request: Autocomplete for interwiki links

### ISSUE THREAD

**Issue by PrivateMandella** [jaap-karssenberg/zim-desktop-wiki#213] opened 2017-09-29 18:15 UTC
I absolutely love Zim. It's easy to use and exactly what I wanted. However, it would be nice if the interwiki linking had an autocomplete feature. It is a really useful feature when linking within the notebook, and would be equally as useful when linking to another page in another notebook. Thanks!

**Comment by jaap-karssenberg** [comment] 2017-12-13 05:22
Duplicate of #158

**Closed by jaap-karssenberg** 2017-12-13 05:22 UTC
Labels: enhancement
