### ISSUE TITLE
Can't move Page/Section to section <Top>

### ISSUE THREAD

**Issue by aetherfaerber** [jaap-karssenberg/zim-desktop-wiki#167] opened 2017-07-27 09:44 UTC
As implied in the title, when moving a page/section (that already exists as directory in the notebooks root folder) to `<Top>` or `<Top>:`, zim throwse the following error:

```
This is zim 0.65
Platform: posix
Locale: de_DE UTF-8
FS encoding: UTF-8
Python: (2, 7, 13, 'final', 0)
Gtk: (2, 24, 31)
Pygtk: (2, 24, 0)
Zim revision is:
  branch: zim-trunk
  revision: 805 jaap.karssenberg@gmail.com-20151101144245-0g7s8a7qjt5xu1d0
  date: 2015-11-01 15:42:45 +0100

======= Traceback =======
  File "/usr/lib/python2.7/dist-packages/zim/gui/widgets.py", line 3106, in do_response
    destroy = self.do_response_ok()
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 3359, in do_response_ok
    newpath = parent + self.path.basename
TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode' 
```

**Comment by jaap-karssenberg** [comment] 2017-09-21 08:25
Can't reproduce in version 0.67

**Comment by jaap-karssenberg** [comment] 2019-01-10 08:31
Closing for now. Please re-open if you have info how to reproduce.

**Closed by jaap-karssenberg** 2019-01-10 08:31 UTC
Labels: needs info
