### ISSUE TITLE
[CRASH] xfce4 panel shortcut init failure (unadulterated source launcher)--01-06-2018_APP//ZIM-v0.67_OS//GalliumOS_DEVICE//ChromebookAcer[Braswell]_BugReport

### ISSUE THREAD

**Issue by ninetyfivenorth** [jaap-karssenberg/zim-desktop-wiki#287] opened 2018-01-06 11:46 UTC
## 

> **[CRASH] xfce4 panel shortcut init failure (unadulterated source launcher)--01-06-2018_APP//ZIM-v0.67_OS//GalliumOS_DEVICE//ChromebookAcer[Braswell]_BugReport**

_xoxo muah_

```
This is zim 0.67
Platform: posix
Locale: en_US UTF-8
FS encoding: UTF-8
Python: (2, 7, 12, 'final', 0)
Gtk: (2, 24, 30)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "/usr/lib/python2.7/dist-packages/zim/main/__init__.py", line 844, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/usr/lib/python2.7/dist-packages/zim/main/__init__.py", line 626, in run
    self._run_cmd(cmd, args) # test seam
  File "/usr/lib/python2.7/dist-packages/zim/main/__init__.py", line 656, in _run_cmd
    self._run_main_loop(cmd)
  File "/usr/lib/python2.7/dist-packages/zim/main/__init__.py", line 697, in _run_main_loop
    w = cmd.run()
  File "/usr/lib/python2.7/dist-packages/zim/main/__init__.py", line 254, in run
    notebook, page = self.build_notebook()
  File "/usr/lib/python2.7/dist-packages/zim/main/__init__.py", line 232, in build_notebook
    notebook, uripage = build_notebook(notebookinfo) # can raise FileNotFound
  File "/usr/lib/python2.7/dist-packages/zim/notebook/__init__.py", line 110, in build_notebook
    notebook = Notebook.new_from_dir(dir)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/notebook.py", line 246, in new_from_dir
    index = Index(cache_dir.file('index.db').path, layout)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/__init__.py", line 67, in __init__
    self._db = self._new_connection()
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/__init__.py", line 85, in _new_connection
    db = sqlite3.Connection(self.dbpath)
OperationalError: unable to open database file


```

**Comment by jaap-karssenberg** [comment] 2018-01-08 10:41
Looks like permissions are missing to access or create the `.zim/index.db` file in the notebook

**Comment by Self-Perfection** [comment] 2018-01-08 15:55
@jaap-karssenberg unable to work with read-only user cache directory looks like a minor bug for me. Indeed, this is extremely rare occasion, but it an be easily handled by fallback to in-memory cache. Kind of:
```
try:
  sqlite3.connect(CACHE_PATH)
except:
  sqlite3.connect("file::memory:?cache=shared")
```

**Comment by jaap-karssenberg** [comment] 2018-01-08 19:18
@Self-Perfection using in memory cache kind of defeats the purpose of caching. It would force zim to index the whole notebook every time you start it, which can take a significant amount of time for large notebooks.

Would like to understand the underlying question better before thinking about a fix. Every system must have a place for applications to store temporary data.

**Comment by ninetyfivenorth** [comment] 2018-01-09 12:15
hey im tossin out the flaw that could possibly happen (because it did so in my environment) but i found my own work arounds as we most do-- if given the prior knowledge to do so. so ya not a worry on my end --- just a heads up to look into :) deuces thanks

**Comment by jaap-karssenberg** [comment] 2019-01-11 08:52
Closing for now, please re-open if you have information on the root cause / how to reproduce

**Closed by jaap-karssenberg** 2019-01-11 08:52 UTC
Labels: needs info
